---
sudo: required
services:
- docker
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/2d5b82a4ed32abc8b684
    - https://api.opsgenie.com/v1/json/travisci?apiKey=3dc220a6-a25a-43c6-a738-2385d41467cf
  on_success: change  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always
  on_start: never     # options: [always|never|change] default: always

script:
- docker build -t scottmiller171/alpine-python:latest .
- docker run scottmiller171/alpine-python:latest python --version
